// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoCommitMessage
{
    internal sealed partial class Vsix
    {
        public const string Id = "AutoCommitMessage.746cce9c-8d32-4825-a32d-80d066e62158";
        public const string Name = "AutoCommitMessage";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "saman azadi";
        public const string Tags = "";
    }
}
