// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace AutoCommitMessage;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string AutoCommitMessageString = "9e692862-5625-4b4d-9139-01b92f417544";
    public static Guid AutoCommitMessage = new Guid(AutoCommitMessageString);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
    public const int MyCommand = 0x0100;
}

